### ISSUE TITLE
Severe slowdown on large files

### ISSUE THREAD

**Issue by NickCondron** [neovim/tree-sitter-vimdoc#6] opened 2022-07-09 23:36 UTC
## Description
Neovim lags severely when moving around large files. The lag gets worse the closer you are to the bottom of the file.
## To reproduce
`:h netrw` (4418 lines)
`G`
Observe slowdown with normal commands or simply holding `k`

**Comment by vigoux** [comment] 2022-07-11 05:58
So the slowdown may be caused by `ERROR` nodes in the file.
I'll try to find out what happened and report it here!

**Comment by clason** [comment] 2022-07-12 08:35
There were some improvements in https://github.com/tree-sitter/tree-sitter recently regarding `ERROR` handling -- you could try building Neovim against the latest tree-sitter commit (e.g., via `.scripts/bump-deps.sh --dep=tree-sitter --HEAD`) and see if that makes a difference?

**Comment by NickCondron** [comment] 2022-07-14 06:52
> There were some improvements in https://github.com/tree-sitter/tree-sitter recently regarding `ERROR` handling -- you could try building Neovim against the latest tree-sitter commit (e.g., via `.scripts/bump-deps.sh --dep=tree-sitter --HEAD`) and see if that makes a difference?

I tested this and it did not fix the issue.

**Comment by vigoux** [comment] 2022-07-14 07:19
Looking into it, there is indeed some `ERRORS` in the file. I'll try to fix them when I have time.

**Comment by justinmk** [comment] 2022-10-09 18:31
seems fixed now. Please test with latest version and say exactly the steps you took

**Closed by justinmk** 2022-10-09 18:31 UTC
