### ISSUE TITLE
parse error: windows.txt 

### ISSUE THREAD

**Issue by mikesmithgh** [neovim/tree-sitter-vimdoc#82] opened 2022-12-28 18:50 UTC
Found `tree-sitter-vimdoc` parse error at: https://neovim.io/doc/user/windows.html

Context:

```

Closing a window
----------------

:q[uit]
:{count}q[uit]						*:count_quit*
CTRL-W q						*CTRL-W_q*
```
![Screenshot 2022-12-28 at 1 48 24 PM](https://user-images.githubusercontent.com/10135646/209858795-1d48420e-9065-477a-8ff2-eead26ece200.png)

**Comment by clason** [comment] 2022-12-28 18:51
Duplicate of #70

**Closed by clason** 2022-12-28 18:51 UTC
