### ISSUE TITLE
parse error: windows.txt 

### ISSUE THREAD

**Issue by dimonzblack** [neovim/tree-sitter-vimdoc#77] opened 2022-12-25 06:12 UTC
![Screenshot_20221210_183651_qrcodescanner barcodescanner qrscanner qrcodereader](https://user-images.githubusercontent.com/117873380/209458674-e229ca3b-0763-4dd7-99b2-3ae07e2b6e71.jpg)
JFound `tree-sitter-vimdoc` parse error at: https://neovim.io/doc/user/windows.html

Context:

```

The argument list and multiple windows
--------------------------------------

The current position in the argument list can be different for each window.
Remember that when doing ":e file", the position in the argument list stays
the same, but you are not editing the file at that position.  To indicate
```

**Comment by dimonzblack** [comment] 2022-12-25 06:12
Hdhyyg

**Comment by clason** [comment] 2022-12-28 12:26
Duplicate of #76 

(what's with your weird spam comments?)

**Closed by clason** 2022-12-28 12:26 UTC
