### ISSUE TITLE
Wrong detection of autocmd paragraph

### ISSUE THREAD

**Issue by bew** [neovim/tree-sitter-vimdoc#106] opened 2023-05-27 09:40 UTC
In the list of autocmds: https://neovim.io/doc/user/autocmd.html#BufRead
At the paragraph for `BufRead or BufReadPost` there seems to be an issue with the detection of the next autocmd paragraph:

![Screenshot_20230527_113729](https://github.com/neovim/tree-sitter-vimdoc/assets/9730330/faa37cad-510e-42b8-90a4-37d3ff0c1e03)

All text is considered part of the paragraph for `BufRead or BufReadPost`, and it only goes back to normal at the next blank line (in the middle of `BufWinEnter`'s paragraph).

Currently `BufRead`, `BufReadCmd`, `BufReadPre`, `BufUnload` & `BufWinEnter` are in the same big paragraph instead of being separated.

**Comment by clason** [comment] 2023-05-27 11:17
Duplicate of #21

**Closed by clason** 2023-05-27 11:17 UTC

**Comment by justinmk** [comment] 2023-06-04 20:22
> Currently `BufRead`, `BufReadCmd`, `BufReadPre`, `BufUnload` & `BufWinEnter` are in the same big paragraph instead of being separated.

As mentioned, known limitation. But also, is it even reasonable for anything except AI to make sense of this structure? It would be quite reasonable to simply add blank lines to the help text.
