### ISSUE TITLE
backtick( and backtick{ start inline code block

### ISSUE THREAD

**Issue by xian-wen** [neovim/tree-sitter-vimdoc#143] opened 2024-10-24 12:27 UTC
Sorry, if this is a duplicate of any other issues, forgive me, please. Thank you so much.
**Problem**
On the latest stable Neovim, the `help.txt` file does not highlight correctly. Especially for characters following ` (single backtick), all are highlighted just like a comment starting from the open backtick to the end of line.
See the details here https://github.com/neovim/neovim/issues/30930.

**Comment by justinmk** [comment] 2024-10-24 12:41
sample text:

```
							*'(* *`(*
'(  `(			To the start of the current sentence, like the |(|
			command.

							*')* *`)*
')  `)			To the end of the current sentence, like the |)|
			command.

							*'{* *`{*
'{  `{			To the start of the current paragraph, like the |{|
			command.

							*'}* *`}*
'}  `}			To the end of the current paragraph, like the |}|
			command.
```

**Comment by justinmk** [comment] 2024-10-24 12:44
I am not sure this is worth "fixing" but can track it here for now.

**Comment by xian-wen** [comment] 2024-10-24 12:49
Thank you so much for the modification. In fact, it is not only backtick( and backtick{, it is backtick<mark>. Any marks following backtick have the same issue. See `:h motion.txt`.

**Comment by clason** [comment] 2024-10-24 12:50
Yes, I don't think this can be solved without lookahead (i.e., an external scanner).

**Comment by justinmk** [comment] 2024-10-24 12:54
> In fact, it is not only backtick( and backtick{, it is backtick(mark). Any marks following backtick have the same issue. See `:h motion.txt`.

Duplicate of https://github.com/neovim/tree-sitter-vimdoc/issues/113

**Closed by justinmk** 2024-10-24 12:54 UTC
Labels: bug
